### ISSUE TITLE
fork之后是无法改为private的

### ISSUE THREAD

**Issue by wzru** [OceanBase-Partner/miniob#1]
![image](https://user-images.githubusercontent.com/28517510/128964280-d345e3cc-c3ee-4ea7-afbd-bbb50ea2793c.png)

**Comment by wzru** [comment]
可以考虑使用阿里云的代码托管服务：https://code.aliyun.com/

**Comment by tyn1998** [comment]
+1

**Comment by Joe978** [comment]
+1

**Comment by Amberjay18** [comment]
+3

**Comment by hnwyllmm** [comment]
自己重新创建一个全新的仓库，设置为private，到时候把代码复制过去可以的

**Comment by wzru** [comment]
@hnwyllmm 那就更改一下README里面的相关描述吧

**Comment by zbtzbtzbt** [comment]
+5
